# Generated by Django 5.1.6 on 2025-02-25 09:11

import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.ActiveUserManager()),
            ],
        ),
    ]
