# Generated by Django 5.1.6 on 2025-02-26 10:14

import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers_payment_stripe_payment_intent_id_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.ActiveUserManager()),
            ],
        ),
    ]
