# Generated by Django 5.1.6 on 2025-02-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                help_text="FCM device token for push notifications",
                max_length=255,
                null=True,
            ),
        ),
    ]
